In [19]:
import numpy as np
import pandas as pd
import math
import statistics

In [20]:
dados = np.array([160, 165, 167, 164, 160, 166, 160, 161, 150, 152, 173, 160, 155,
                  164, 168, 162, 161, 168, 163, 156, 155, 169, 151, 170, 164,
                  155, 152, 163, 160, 155, 157, 156, 158, 158, 161, 154, 161, 156, 172, 153])
dados

array([160, 165, 167, 164, 160, 166, 160, 161, 150, 152, 173, 160, 155,
       164, 168, 162, 161, 168, 163, 156, 155, 169, 151, 170, 164, 155,
       152, 163, 160, 155, 157, 156, 158, 158, 161, 154, 161, 156, 172,
       153])

In [21]:
total_amplitude = dados.max() - dados.min()
total_amplitude

23

In [22]:
q1 = np.quantile(dados, 0.25)
q2 = np.median(dados)
q3 = np.quantile(dados, 0.75)
q1, q2, q3

(155.75, 160.0, 164.0)

In [23]:
interq_difference = q3 - q1
interq_difference

8.25

In [24]:
inferior = q1 - (1.5 * interq_difference)
superior = q3 + (1.5 * interq_difference)
inferior, superior

(143.375, 176.375)

ESTUDO

In [66]:
data = np.array([120, 80, 130, 143, 132, 98, 124, 120, 512, 155, 875])
data

array([120,  80, 130, 143, 132,  98, 124, 120, 512, 155, 875])

In [67]:
data = np.sort(data)
data

array([ 80,  98, 120, 120, 124, 130, 132, 143, 155, 512, 875])

In [68]:
q1 = np.quantile(data, 0.25)
q3 = np.quantile(data, 0.75)
q1, q3

(120.0, 149.0)

In [69]:
di = q3 - q1
di

29.0

In [70]:
outlier_inf = q1 - (1.5 * di)
outlier_sup = q3 + (1.5 * di)
outlier_inf, outlier_sup

(76.5, 192.5)

In [81]:
outliers = []
for registro in data:
    if registro < outlier_inf or registro > outlier_sup:
        outliers.append(registro)

data_clear = [valor for valor in data if valor not in outliers]
data_clear

[80, 98, 120, 120, 124, 130, 132, 143, 155]