In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
np.random.rand(50)

array([0.77958974, 0.63097927, 0.79273495, 0.84279219, 0.55180797,
       0.13845554, 0.7625272 , 0.74843285, 0.44063963, 0.94493064,
       0.85064857, 0.72833921, 0.97931482, 0.17085045, 0.40707152,
       0.87324956, 0.72848349, 0.18820996, 0.60387068, 0.71871504,
       0.68648971, 0.26697177, 0.35495799, 0.09185906, 0.14833803,
       0.00131524, 0.72486551, 0.64490255, 0.22484929, 0.77314437,
       0.00695664, 0.34731782, 0.89917714, 0.084424  , 0.34779689,
       0.64580236, 0.37399708, 0.88324238, 0.1913062 , 0.5502106 ,
       0.93179153, 0.78669835, 0.33513787, 0.14595361, 0.07785359,
       0.0486817 , 0.73674255, 0.11441838, 0.33564575, 0.18084072])

In [3]:
np.random.randint(0, 2)

0

In [31]:
base_selecao = {'a': np.random.rand(20), 'b': np.array([0.5] * 20), 'classe': np.random.randint(0, 2, size = 20)}
base_selecao

{'a': array([0.34412712, 0.53593362, 0.14662557, 0.618975  , 0.81365146,
        0.97778479, 0.27164237, 0.83065555, 0.62075331, 0.10287599,
        0.51137608, 0.23993849, 0.19006188, 0.05918208, 0.45539104,
        0.24076667, 0.49283288, 0.53479786, 0.30261677, 0.96269319]),
 'b': array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]),
 'classe': array([0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1])}

In [32]:
dataset = pd.DataFrame(base_selecao)
dataset.head()

a    b  classe
0  0.344127  0.5       0
1  0.535934  0.5       1
2  0.146626  0.5       0
3  0.618975  0.5       1
4  0.813651  0.5       1

In [33]:
dataset.describe()

a     b    classe
count  20.000000  20.0  20.00000
mean    0.462634   0.5   0.65000
std     0.278979   0.0   0.48936
min     0.059182   0.5   0.00000
25%     0.240560   0.5   0.00000
50%     0.474112   0.5   1.00000
75%     0.619420   0.5   1.00000
max     0.977785   0.5   1.00000

In [34]:
np.var(dataset['a']), np.var(dataset['b'])

(0.0739379653604435, 0.0)

In [35]:
X = dataset.iloc[:,0:2].values
y = dataset.iloc[:,2].values
X, y

(array([[0.34412712, 0.5       ],
        [0.53593362, 0.5       ],
        [0.14662557, 0.5       ],
        [0.618975  , 0.5       ],
        [0.81365146, 0.5       ],
        [0.97778479, 0.5       ],
        [0.27164237, 0.5       ],
        [0.83065555, 0.5       ],
        [0.62075331, 0.5       ],
        [0.10287599, 0.5       ],
        [0.51137608, 0.5       ],
        [0.23993849, 0.5       ],
        [0.19006188, 0.5       ],
        [0.05918208, 0.5       ],
        [0.45539104, 0.5       ],
        [0.24076667, 0.5       ],
        [0.49283288, 0.5       ],
        [0.53479786, 0.5       ],
        [0.30261677, 0.5       ],
        [0.96269319, 0.5       ]]),
 array([0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1]))

In [36]:
from sklearn.feature_selection import VarianceThreshold

In [38]:
selecao = VarianceThreshold(threshold = 0.07) #Excluir valores com variância menor
X_novo = selecao.fit_transform(X)

In [39]:
X_novo, X_novo.shape

(array([[0.34412712],
        [0.53593362],
        [0.14662557],
        [0.618975  ],
        [0.81365146],
        [0.97778479],
        [0.27164237],
        [0.83065555],
        [0.62075331],
        [0.10287599],
        [0.51137608],
        [0.23993849],
        [0.19006188],
        [0.05918208],
        [0.45539104],
        [0.24076667],
        [0.49283288],
        [0.53479786],
        [0.30261677],
        [0.96269319]]),
 (20, 1))

In [40]:
selecao.variances_

array([0.07393797, 0.        ])

In [41]:
indices = np.where(selecao.variances_ > 0.07)
indices

(array([0], dtype=int64),)