Importação das bibliotecas

In [40]:
import pandas as pd
import random
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.under_sampling import TomekLinks

In [41]:
dataset = pd.read_csv('credit_data.csv')
dataset.dropna(inplace=True)

In [42]:
X = dataset.iloc[:,1:4].values
y = dataset.iloc[:,4].values

In [43]:
X.shape, y.shape

((1997, 3), (1997,))

In [58]:
tl = TomekLinks(sampling_strategy='majority') # 'majority' irá apagar dados apenas da classe majoritária, 'all' apagaria de ambos
X_under, y_under = tl.fit_resample(X, y)

In [59]:
X_under.shape, y_under.shape

((1897, 3), (1897,))

In [65]:
np.unique(y, return_counts=True)

(array([0, 1], dtype=int64), array([1714,  283], dtype=int64))

In [66]:
np.unique(y_under, return_counts=True)

(array([0, 1], dtype=int64), array([1614,  283], dtype=int64))

In [70]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X_under, y_under, test_size = 0.2, stratify=y_under)

In [71]:
X_treinamento.shape, X_teste.shape

((1517, 3), (380, 3))

In [76]:
modelo = GaussianNB()
modelo.fit(X_treinamento,y_treinamento)
previsoes = modelo.predict(X_teste)
accuracy_score(previsoes, y_teste)

0.9289473684210526

In [77]:
confusion_matrix(previsoes, y_teste)

array([[320,  24],
       [  3,  33]], dtype=int64)